### ISSUE TITLE
'year' Key error

### ISSUE THREAD

**Issue by ghost** [thetvdb/tvdb-v4-python#26]
TheTVDB.com Series ID
332802 
tvdb V1.06 and V1.07

`tvdb = tvdb_v4_official.TVDB("", pin="")
title = 'grown-ish'

series = tvdb.search(title)
for item in series:
   print(item['name'], item['year'], item['tvdb_id'])
`
Hi 
if your search for 'grown-ish' it works and I can get the year key value, but if you change : 

title = 'grown-ish'
to
title = 'grown ish'  

the code return : KeyError: 'year'
if you only print item you can see everything including the year value and website has no issue
thank you for your time

**Comment by mibj** [comment]
upgraded to 1.07 . Solved Thanks

**Comment by ghost** [comment]
thought it was solved with 1.07. But it still returns key error

**Comment by maxifwortman** [comment]
@mibj That's because you are getting a people record in the results, you can check the search results by printing the reponse like:

```
title = 'grown ish'
series = tvdb.search(title)
print(series)
```
You will see that the reponse is including person-8944053. Also, you can filter the results to only include series like this:

`series = tvdb.search(title, type="series")`

**Comment by ghost** [comment]
Ok great , Thank you
